[package]
name = "frabjous-bitcoin"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.4"

[profile.dev]
opt-level = 1
overflow-checks = false

[[bin]]
name = "frabjous-bitcoin"
path = "src/main.rs"
